# Generated by Django 4.0.2 on 2022-02-16 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopping', '0002_plan_remove_meal_weekly_plan_delete_weeklyplan_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ingredient',
            name='meal',
        ),
        migrations.AddField(
            model_name='mealingredient',
            name='meal',
            field=models.ManyToManyField(blank=True, to='shopping.Meal'),
        ),
    ]
