# Generated by Django 4.0.2 on 2022-02-16 14:24

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopping', '0003_remove_ingredient_meal_mealingredient_meal'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aisle',
            name='number',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.RemoveField(
            model_name='section',
            name='aisle',
        ),
        migrations.AddField(
            model_name='section',
            name='aisle',
            field=models.ManyToManyField(blank=True, null=True, to='shopping.Aisle'),
        ),
    ]
