# Generated by Django 4.0.2 on 2022-02-16 14:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shopping', '0004_alter_aisle_number_remove_section_aisle_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='StoreAisle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shopping.store')),
            ],
        ),
        migrations.RemoveField(
            model_name='section',
            name='aisle',
        ),
        migrations.DeleteModel(
            name='Aisle',
        ),
        migrations.AddField(
            model_name='section',
            name='store_aisle',
            field=models.ManyToManyField(blank=True, to='shopping.StoreAisle'),
        ),
    ]
