# Generated by Django 4.0.2 on 2022-02-16 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopping', '0005_storeaisle_remove_section_aisle_delete_aisle_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='store',
            name='aisles',
            field=models.IntegerField(default=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='storeaisle',
            name='number',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
