# Generated by Django 4.0.2 on 2022-02-16 15:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shopping', '0007_remove_section_store_aisle_storeaisle_section'),
    ]

    operations = [
        migrations.RenameField(
            model_name='storeaisle',
            old_name='number',
            new_name='aisle_number',
        ),
    ]
