# Generated by Django 4.0.2 on 2022-02-16 15:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shopping', '0008_rename_number_storeaisle_aisle_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='store',
            name='aisles',
        ),
    ]
