# Generated by Django 4.0.2 on 2022-02-16 15:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shopping', '0009_remove_store_aisles'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mealingredient',
            name='meal',
        ),
        migrations.AddField(
            model_name='mealingredient',
            name='meal',
            field=models.ForeignKey(blank=True, default=1, on_delete=django.db.models.deletion.CASCADE, to='shopping.meal'),
            preserve_default=False,
        ),
    ]
