# Generated by Django 4.0.2 on 2022-02-16 15:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shopping', '0010_remove_mealingredient_meal_mealingredient_meal'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mealingredient',
            name='user',
        ),
    ]
