# Generated by Django 4.0.2 on 2022-02-16 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopping', '0011_remove_mealingredient_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='plan',
            name='last_update',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='mealingredient',
            name='unit',
            field=models.CharField(choices=[(' x ', 'Items'), ('g', 'Grams'), ('kg', 'Kilograms'), ('ml', 'Millilitres'), ('l', 'Litres')], max_length=255),
        ),
    ]
