# Generated by Django 4.0.2 on 2022-02-16 16:10

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('shopping', '0012_plan_last_update_alter_mealingredient_unit'),
    ]

    operations = [
        migrations.AddField(
            model_name='ingredient',
            name='added',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
