# Generated by Django 4.0.2 on 2022-02-17 10:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shopping', '0015_plan_added_section_added_store_added'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='plan',
            name='days',
        ),
    ]
