# Generated by Django 4.0.2 on 2022-02-17 10:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shopping', '0016_remove_plan_days'),
    ]

    operations = [
        migrations.CreateModel(
            name='Day',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shopping.meal')),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shopping.plan')),
            ],
        ),
    ]
