# Generated by Django 4.0.2 on 2022-02-17 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopping', '0017_day'),
    ]

    operations = [
        migrations.AddField(
            model_name='day',
            name='order',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
