# Generated by Django 4.0.2 on 2022-02-17 10:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shopping', '0018_day_order'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='meal',
            name='plan',
        ),
    ]
