# Generated by Django 4.0.2 on 2022-02-25 12:15

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shopping', '0019_remove_meal_plan'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='day',
            options={'ordering': ['order']},
        ),
        migrations.AlterModelOptions(
            name='ingredient',
            options={'ordering': ['section', 'name']},
        ),
        migrations.AlterField(
            model_name='day',
            name='meal',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plan_meals', to='shopping.meal'),
        ),
        migrations.AlterField(
            model_name='day',
            name='order',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AlterField(
            model_name='day',
            name='plan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plan_days', to='shopping.plan'),
        ),
        migrations.AlterField(
            model_name='mealingredient',
            name='ingredient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='actual_ingredient', to='shopping.ingredient'),
        ),
        migrations.AlterField(
            model_name='mealingredient',
            name='meal',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='meal_ingredients', to='shopping.meal'),
        ),
        migrations.AlterField(
            model_name='storeaisle',
            name='section',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shopping.section'),
        ),
    ]
