# Generated by Django 4.0.4 on 2022-05-12 15:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shopping', '0021_alter_mealingredient_quantity_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='day',
            name='meal',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shopping.meal'),
        ),
        migrations.AlterField(
            model_name='day',
            name='plan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shopping.plan'),
        ),
    ]
