# Generated by Django 4.0.4 on 2022-05-18 12:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shopping', '0022_alter_day_meal_alter_day_plan'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='storeaisle',
            unique_together={('store', 'section')},
        ),
    ]
