# Generated by Django 4.0.4 on 2022-05-24 11:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shopping', '0023_alter_storeaisle_unique_together'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='storeaisle',
            options={'ordering': ['aisle_number', 'section__name']},
        ),
        migrations.AlterUniqueTogether(
            name='storeaisle',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='storeaisle',
            name='store',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='aisles', to='shopping.store'),
        ),
    ]
