# Generated by Django 4.0.4 on 2022-06-13 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopping', '0024_alter_storeaisle_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='meal',
            name='recipe',
            field=models.TextField(blank=True),
        ),
    ]
